HSLdevcom/digitransit-proxy

Dockerfile, common.conf, nginx.conf
4g cache can store about half a million searches.
=> Cache geocoding searches

nginx.conf
$server_name takes the first of the declared names, in this case the dev ones.
=> Do not redirect from http beta to https dev

nginx.conf
adds reittiopas hameelinna domain to proxy config.
=> added hameenlinna to proxy

nginx.conf
More workers to allow increase the number of processes creating connection from 1 to 3 to allow better utilization of underlying compute capacity.
=> updated the nginx workers

external.conf
lets make this consistent so that the dev IP range is also in the ACL.
=> added dev IP range for ACL

nginx.conf, test.js, test.sh
* sentry-analytics.digitransit.fi domain
=> Sentry analytics

external.conf, run.sh, test.js, test.sh
* New samocat endpoint
* Replace liikennevirasto address with new one (but keep old one until it's not being used anywhere anymore)
=> Samocat external

external.conf, run.sh, test.sh
* Add lahti external endpoint for fetching RT data
* Rename HSL_PROD_RT env variable to HSL_RT_STORAGE_NAME
=> Lahti external

external.conf, run.sh, test.sh
- added matkahuolto proxy for gtfs data
=> Add matkahuolto proxy

.travis.yml, common.conf, nginx.conf, test.js, travis-build.sh
* Remove cache from most endpoints as we do it now in API management
* Don't set X-Forwarded-Host header as we do it now in API management
=> Merge preparation

Dockerfile
=> Upgrade nginx version

nginx.conf
* Removes nginx version from response header
=> Hide nginx version from responses

external.conf
* Removes old väylä external endpoint
* Removes duplicate next bike external endpoint
* Adds vilkku external endpoint
=> Add vilkku bikes

Dockerfile
Upgade nginx to latest stable version.
=> Upgrade nginx version to 1.18

nginx.conf, test.js
* Adds couple of new domains used for digitransit-ui-hsl-next
=> Add new domains for digitransit-ui-hsl-next

nginx.conf, run.sh, test.js, test.sh
* Added redirect from next ui root paths to configurable hsl.fi URL
=> hsl.fi redirect from next ui root path

external.conf
=> DT-4675: Add city bikes to Tampere's instance

basicsettings.conf, nginx.conf, test.js
- Allow embedding of the new search view
- Moved some basic settings to a portable module so reduce repetition
- Added few basic tests
=> Allow embedding of the new search view

common.conf, nginx.conf, test.js
* Adds v2 (replaces "next") and v3 ui (for future ui development to use otp2 API) endpoints.
* Removes support for unused domains
=> UI updates

external.conf, run.sh, test.sh
* Adds vantaa citybike external endpoint
* Removes some legacy citybike external endpoints that are no longer in use
=> Add Vantaa citybike external endpoint

test.sh, tools/getMyLocalIp.js
- Use os.networkInterfaces() function for local ip address detection
- Fix some ShellCheck linter issues in test.sh
=> Improve test script cross-platform portability

nginx.conf
=> Route new service (VARELY) to digitransit-ui-waltti-v2 container

common.conf
=> Fix rewrite path regexp for v2-test/hsl

common.conf, test.js
We have an issue with our CDN that it doesn't support caching based on accept-language header, therefore we need to include the language in the path.
=> Update new vector tile endpoints

common.conf, nginx.conf
- Remove subscription key from cache key as with geocoding
=> change map proxy cache key

nginx.conf, test.js
* Remove linjasto2021 and sentry-analytics domain support as they will no longer be used
=> Remove couple of old unused domains

common.conf
Merge after first data build is run
=> Add kela data container

external.conf
- added Lahti city bikes to proxy settings
=> dt-5924 proxy for lahti city bikes

external.conf
- Raasepori gtfs proxy configuration added
=> dt-5980 raasepori gtfs proxy config

run.sh, test.sh
- Raasepori run.sh config added
=> dt-5980 raasepori run config

nginx.conf, test.js
New Raasepori instance proxy config
=> dt-6033 raasepori config

external.conf, run.sh, test.sh
- proxy config for varely RT data
=> DT-5977 varely rt proxy

common.conf, test.js
We will remove the old endpoints in a follow up pr
=> Add new kela routing and map endpoints

external.conf
- proxy for the new GTFS-RT test address
=> DT-6282 new tampere test gtfsrt proxy

nginx.conf, test.js
https://github.com/HSLdevcom/digitransit-ui/pull/4995
=> DT-6274 Walttiopas embedded search comes up on google before opas.waltti.fi
